name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: powershell allow...
      shell: cmd
      run: powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"
    - name: check powershell version
      run: $host.Version
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag take-a-seat:$(date -uFormat +%s)
